//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Spectra4.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_SPECTRTYPE                  129
#define IDR_COMP_TOOLBAR                134
#define IDD_DIALOG1                     136
#define IDD_SPECGRID_DLG                137
#define IDD_DLG_AXES                    138
#define IDD_DLG_SCAN                    139
#define IDD_FITSET                      140
#define IDD_RAND_DLG                    144
#define IDD_TOOLS_OPTS                  145
#define IDD_TOOLS_HIST                  146
#define IDD_FITRES                      147
#define IDD_TRACE_NUM                   148
#define IDR_SPECTRTYPE1                 150
#define IDD_TMCOURSE                    150
#define IDB_BITMAP1                     152
#define IDD_SCALE_DLG                   153
#define IDD_SEEK_FIT                    154
#define IDD_VARAN_SET                   155
#define IDC_BUTTON1                     1000
#define IDC_AX_APPLY                    1000
#define IDC_FITRES_TRY                  1000
#define IDC_LIST1                       1001
#define IDC_EDIT1                       1003
#define IDC_SCAN_NUM                    1003
#define IDC_FITSET_CICLE                1003
#define IDC_RAND_LOW                    1003
#define IDC_OPTS_BEF                    1003
#define IDC_HIST_BEGP                   1003
#define IDC_FITRES_MAX                  1003
#define IDC_TRACENUM_FROM               1003
#define IDC_EDIT2                       1004
#define IDC_FITSET_STEP                 1004
#define IDC_RAND_HIGH                   1004
#define IDC_POTS_AFT                    1004
#define IDC_HIST_ENDP                   1004
#define IDC_FITRES_TRISE                1004
#define IDC_TRACENUM_TO                 1004
#define IDC_COMBO1                      1005
#define IDC_FITSET_AC_LOW               1005
#define IDC_FITRES_TDEC                 1005
#define IDC_FACTOR_COMBO                1005
#define IDC_FITSEEK_TR1                 1005
#define IDC_TREE1                       1006
#define IDC_FITSET_AC_HIGH              1006
#define IDC_FITRES_AMP                  1006
#define IDC_FITSEEK_TR2                 1006
#define IDC_COMBOBOXEX1                 1007
#define IDC_FITSEEK_TD1                 1007
#define IDC_FITRES_MAX2                 1007
#define IDC_FITSEEK_TD2                 1008
#define IDC_FITRES_TRISE2               1008
#define IDC_GRIDCTRL                    1009
#define IDC_FITRES_TDEC2                1009
#define IDC_FITRES_AMP2                 1010
#define IDC_EDIT3                       1016
#define IDC_OPTS_STIM                   1016
#define IDC_HIST_NBIN                   1016
#define IDC_FITSET_TY                   1016
#define IDC_TDEC                        1016
#define IDC_EDIT4                       1017
#define IDC_FITSET_LOWX                 1017
#define IDC_OPT_DEPTH                   1017
#define IDC_EDIT5                       1018
#define IDC_AX_END                      1018
#define IDC_OPTS_CREATE                 1018
#define IDC_HIST_BIN                    1018
#define IDC_FITSET_HIGHX                1018
#define IDC_EDIT6                       1019
#define IDC_OPTS_MAXPOINT               1019
#define IDC_EDIT7                       1020
#define IDC_EDIT8                       1021
#define IDC_AX_BEG                      1021
#define IDC_EDIT9                       1022
#define IDC_LIST2                       1023
#define IDC_FIT_MODE                    1023
#define IDC_CHAN_LIST                   1023
#define IDC_AX_X                        1026
#define IDC_AX_Y                        1027
#define IDC_SCAN_MIN                    1028
#define IDC_SCAN_MAX                    1029
#define IDC_SCAN_AVE                    1030
#define IDC_SCAN_SLP                    1031
#define IDC_SCAN_ARE                    1032
#define IDC_FIT_PARAM                   1034
#define IDC_FIT_NUM                     1035
#define IDC_OPT_SWPSER                  1036
#define IDC_FITSET_MDIN                 1037
#define IDC_FITSET_MDOUT                1038
#define IDC_FITRES_SWN                  1038
#define IDC_FITSET_MDGS                 1039
#define IDC_FITRES_PKN                  1039
#define IDC_FITRES_SGN                  1040
#define IDC_FITRES_ACCUR                1041
#define IDC_FITRES_STOP                 1044
#define IDC_BEG                         1047
#define IDC_END                         1048
#define IDC_FITSEEK_AMP2                1051
#define IDC_FITSEEK_AMP1                1052
#define IDC_STATIC_HIGH                 1055
#define IDC_STATIC_LOW                  1056
#define IDC_NS_BEG                      1058
#define IDC_AN_BEG                      1059
#define IDC_NS_END                      1061
#define IDC_AN_END                      1062
#define IDC_FIT_MIX                     1064
#define IDC_AXIS_LF                     1066
#define IDC_AXIS_MN                     1067
#define IDC_AXIS_PL                     1068
#define IDC_FITRES_ZERO                 1068
#define IDC_AXIS_RT                     1069
#define IDC_FITRES_ZERO2                1069
#define IDC_AXIS_RESET                  1070
#define IDC_CUMHST                      1071
#define ID_FILE_NEWSPEC                 32771
#define ID_WINDOW_CLOSEALL              32772
#define ID_COMP_NEW                     32774
#define ID_COMP_DEL                     32775
#define ID_COMP_ALIGN                   32776
#define ID_COMP_DIALOGBAR               32777
#define ID_AXIS_X                       32778
#define ID_AXIS_Y                       32779
#define ID_SPEC_APPLY                   32780
#define ID_COMP_MANAG                   32781
#define ID_SPEC_AVER                    32782
#define ID_TOOLS_SCAN                   32783
#define ID_FIT_TRACE                    32784
#define ID_FIT_MONTEC                   32785
#define ID_FIT_SET                      32786
#define ID_TOOLS_OPTS                   32787
#define ID_FIT_STEP                     32789
#define ID_FIT_SUMM                     32793
#define ID_FIT_AUTO                     32795
#define ID_BUTTON32796                  32796
#define ID_FIT_RAND                     32800
#define ID_MONTECAR_RAND                32801
#define ID_MONTECAR_LLH                 32802
#define ID_MONTECAR_AC                  32803
#define ID_TOOLS_AC                     32804
#define ID_TOOLS_HIST                   32805
#define ID_COMP_CREATE                  32806
#define ID_SPEC_RANDOM                  32807
#define ID_FIT_FIND                     32809
#define ID_TOOLS_MINIAN                 32811
#define ID_TOOLS_LLHTEST                32812
#define ID_LOT_LOAD                     32813
#define ID_LOT_ANAL                     32814
#define ID_LOT_PRED                     32815
#define ID_TOOLS_SMOOTH                 32816
#define ID_TOOLS_EXTRAP                 32817
#define ID_TOOLS_SEEK                   32818
#define ID_TOOLS_AREA                   32819
#define ID_TOOLS_TMCOUR                 32820
#define ID_LOT_RATE_HST                 32821
#define ID_TOOLS_PWSPEC                 32822
#define ID_LOT_RATE_PLACE               32823
#define ID_TOOLS_FFT                    32824
#define ID_TOOLS_FFTR                   32825
#define ID_TOOLS_SCALE                  32826
#define ID_FIT_REM_DUPL                 32827
#define ID_TOOLS_VARAN                  32828
#define ID_COMP_CLIP                    32829
#define ID_SEL_TOGGLE                   32830
#define ID_TOOLS_SLOPE                  32831
#define IDS_SPEC_TITLE                  61216
#define IDS_SPEC_FITTRACE               61217
#define IDS_SPEC_SLOPE                  61218
#define IDS_SPEC_SCAN                   61219
#define IDS_SPEC_HIST                   61220
#define IDS_INDICAT1                    61221
#define IDS_INDICAT2                    61222
#define IDS_INDICAT3                    61223
#define IDS_INDICAT4                    61224

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
